### ISSUE TITLE
A question of the function 'get_projected_weight()' in class LangPuller

### ISSUE THREAD

**Issue by YAaNnGg** [feyzaakyurek/subspace-reg#13]
Hi, thanks for your inspiring work and detailed doc. 

```
  def get_projected_weight(self, pull, base_weight, weights):
      tr = torch.transpose(base_weight, 0, 1)
      Q, R = torch.qr(tr, some=True) # Q is 640x60
      mut = weights @ Q # mut is 5 x 60
      mutnorm = mut / torch.norm(base_weight, dim=1).unsqueeze(0)
      return mutnorm @ base_weight
```

I wonder if there is a mistake when getting the projection vector 'm'. In my opinion, 'mut' is the coordinate of the orthogonal basis and the projection should be derived from `mut @ Q` instead of `mut @ base_weight`.  Please let me know if I were wrong. 

Thanks a lot!

**Comment by feyzaakyurek** [comment]
Hi @YAaNnGg, thank you so much for pointing this out. I think you are right.

I've fixed the code and rerun the respective experiments, which significantly improved the results for subspace regularizer. I would be happy to acknowledge you if you'd like to provide your name.

Again, thank you!

**Comment by YAaNnGg** [comment]
Oh, that sounds great!

Sorry for the late reply, I've been busy with something else in the past weeks. I am also pleased to help improve the code. My name is Chenyang Wang, feel free not to acknowledge me if inconvenient now.
