### ISSUE TITLE
A question of the determine statement 'if [[ $cnt -eq $SLURM_ARRAY_TASK_ID ]]' in sample scripts

### ISSUE THREAD

**Issue by hwanyu112** [feyzaakyurek/subspace-reg#14]
Hi, thanks for your inspiring work and detailed doc.
When I ran the sample scripts following your guide, I found that the value of `SLURM_ARRAY_TASK_ID`  is unknown. As a result, no log files were output. So I commented out the whole line `if [[ $cnt -eq $SLURM_ARRAY_TASK_ID ]]; then` and gave a random value to `SLURM_ARRAY_TASK_ID`, then everything seemed to be work properly. 
I wonder whether the value of `SLURM_ARRAY_TASK_ID`  and the determine statement in sample scripts is necessary or not. Please let me know if I miss anything important.
Thanks a lot!

**Comment by feyzaakyurek** [comment]
Hi @hwanyu112,

Thanks for your interest! The cluster I've been using used Slurm as the scheduler and I use the nested for loop for hyper parameter tuning. If you don't have Slurm, you can actually just ignore the nested for loop; it's just for assigning jobs to different GPUs. 

Instead, in every script, I provide the simple calls you can run, see https://github.com/feyzaakyurek/subspace-reg/blob/master/scripts/continual/slurm_subspace_reg.sh#L63
