### ISSUE TITLE
How to run and reproduce experimental results

### ISSUE THREAD

**Issue by ElifCerenGokYildirim** [feyzaakyurek/subspace-reg#15]
Hi, 
Thanks for this great study. I would like to reproduce you experimental results but I am not sure which file to run to get the experimental results. I followed the instructions from the README file for downloading and extracting files. I ran the` train_supervised.py` file but got the following error: 
FileNotFoundError: [Errno 2] No such file or directory: './data/miniImageNet\\miniImageNet_category_split_train_phase_train.pickle'
It would be amazing if you could share how to use your code for reproducing the experiment results or using it for another datasets. 
Thank you so much!

**Comment by feyzaakyurek** [comment]
Hi @ElifCerenGok, glad that you found it interesting!

The path 

'./data/miniImageNet\miniImageNet_category_split_train_phase_train.pickle'

seems to have both / and \\. I think your system may be using \ to separate directories. If that's the case, you would need to set the path variables such as `--data_root` to be compatible with your system. 

Hope this helps.
